//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodekassen.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fine
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Price { get; set; }
        public int PlayerId { get; set; }
    
        public virtual FineType FineType { get; set; }
        public virtual Player Player { get; set; }
    }
}
